# Generated by Django 2.1.5 on 2019-02-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190203_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [['can_view_post', 'Can view post']]},
        ),
    ]
