# Generated by Django 2.1.5 on 2019-02-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='content',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
    ]
