# Generated by Django 2.1.5 on 2019-02-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20190205_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
