# Generated by Django 2.1.5 on 2019-02-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_auto_20190206_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=models.TextField(default='Some String'),
        ),
    ]
